---
sidebar: sidebar 
permalink: support/autosupport.html 
keywords: how to use autosupport, autosupport, asup, logs, asup bundle, support ticket, support bundle 
summary: NetApp 通过多种方式为 Astra Data Store 预览版提供支持。全天候提供丰富的免费自助支持选项，例如知识库（ KB ）文章和可宽延的渠道。您的 Astra Data Store 预览帐户包括通过 Web 服务单提供的远程技术支持。 
---
= 自动支持监控
:hardbreaks:
:icons: font
:imagesdir: ../media/support/


AutoSupport 监控 Astra 数据存储预览系统运行时间和信息，并向 NetApp 支持部门发送消息。根据您的配置，可以监控以下系统组件：

* 控制面板
* 存储


默认情况下，期间会启用 AutoSupport link:../get-started/install-ads.html#install-the-astra-data-store-cluster["Astra Data Store 预览集群安装"] 或者在将 AutoSupport CR 应用于集群后。启用后， AutoSupport （ ASUP ）捆绑包将自动上传到 NetApp 支持站点（ NSS ）或可供手动下载。

.选项
* <<AutoSupport triggers and scenarios>>
* <<Configure custom control plane AutoSupport collection>>
* <<Configure custom storage AutoSupport collection>>
* <<List ASUPs in the system>>
* <<Download an ASUP Bundle>>




== AutoSupport 触发器和场景

AutoSupport 捆绑包可通过以下方式触发：

* 定期： ASUP 捆绑包按 CR 中定义的间隔创建。
* User triggered ：您可以手动创建自己的 ASUP 以查看日志。
* 核心转储：如果节点上存在核心转储，则会生成 ASUP ，并将核心发送给 NetApp 进行进一步调查。
* 基于 CallHome 事件：从操作系统的特定 CallHome 事件生成 ASUP 。
* 基于 Kubernetes 事件：通过控制平面中的特定 Kubernetes 事件生成 ASUP 。


这些触发情形会生成以下 AutoSupport 类型之一：

* ControlPlane AutoSupport ：一组 Astra 数据存储预览控制平面日志和 CRS 。
* Storage AutoSupport ：存储报告和性能数据的集合。
* 核心转储 AutoSupport ：系统核心转储的集合。




== 配置自定义控制平面 AutoSupport 收集

您可以创建一个自定义 AutoSupport 收集配置，用于报告控制平面事件。默认情况下，大多数安装都已在期间启用定期事件报告 link:../get-started/install-ads.html#install-the-astra-data-store-cluster["Astra Data Store 预览集群安装"]。此操作步骤介绍如何配置 AutoSupport CR ，以便根据您选择的参数进行报告：

.步骤
. 自定义以下命令以创建控制面板集合 CR ：
+
[listing]
----
kubectl astasds asup collect -c controlplane --namespace=astrads-system
----
+
.. 定义自定义参数：
+
*** ` <myASUPname>` ：要生成的 AutoSupport CR 的名称。
*** ` -e < 事件名称 >` ：触发收集事件名称的事件名称应在 component-YAML （挂载到支持控制器）中预定义。
+
示例

+
[listing]
----
kubectl astrasds asup collect -c controlplane custom-asup-name -e debug --namespace=astrads-system
----


.. 根据需要为系统添加其他参数：
+
*** ` -cluster` ：在多集群环境中需要此标志。
*** ` -localCollection` ：启用本地收集。默认值为 `false 。`
*** ` -forceUpload` ：启用强制上传。默认值为 `false 。`
*** ` — retry` ：启用重试。默认值为 `false 。`








== 配置自定义 Storage AutoSupport 收集

您可以创建自定义 AutoSupport 收集配置，以报告存储组件事件。默认情况下，大多数安装都已在期间启用定期事件报告 link:../get-started/install-ads.html#install-the-astra-data-store-cluster["Astra Data Store 预览集群安装"]。此操作步骤介绍如何配置 AutoSupport CR ，以便根据您选择的参数进行报告：

.步骤
. 自定义以下命令以创建存储收集 CR ：
+
[listing]
----
kubectl astrasds asup collect -c storage --namespace=astrads-system
----
+
.. 定义自定义参数：
+
*** ` <myASUPname>` ：要生成的 AutoSupport CR 的名称。
*** ` -e < 事件名称 >` ：触发收集事件名称的事件名称应在 component-YAML （挂载到支持控制器）中预定义。
+
性能事件示例：

+
[listing]
----
kubectl-astrads asup collect -c storage -e performance example-perf-storage-asup
----
*** ` -t <ISO_format> -d <hours>` ：在指定的持续时间内为所有节点收集存储 ASUP 。请使用标准 ISO 日期时间格式（` -t` ），持续时间（ `D` ）以小时为单位。例如：
+
[listing]
----
kubectl astrads asup collect -c storage -t 2021-01-01T15:00:00Z -d 24
----
*** ` -nodes < 节点名称 >` ：为指定节点收集存储 ASUP 。例如：
+
[listing]
----
kubectl astrads asup collect -c storage --nodes example1
----
*** ` -nodes nodename1 ， nodeame2 ， nodeame3` ：为指定节点收集存储 ASUP ：
+
[listing]
----
kubectl astrads asup collect -c storage --nodes example1,example2,example3
----


.. 根据需要为系统添加其他参数：
+
*** ` -cluster` ：在多集群环境中需要此标志。
*** ` -localCollection` ：启用本地收集。默认值为 `false 。`
*** ` -forceUpload` ：启用强制上传。默认值为 `false 。`
*** ` — retry` ：启用重试。默认值为 `false 。`








== 列出系统中的 ASUP

使用以下命令按名称列出系统中的 ASUP ：

[listing]
----
kubectl astrasds asup list --namespace=astrads-system
----
响应示例：

[listing]
----
NAMESPACE      NAME                                                SEQUENCE NUMBER EVENT                           SIZE    STATE       LOCAL COLLECTION
astrads-system  storage-callhome.reboot.unknown-20211115t182151...  1               callhome.reboot.unknown         0       uploaded    astrads-ds-support-tdl2h:
astrads-system  storage-callhome.reboot.unknown-20211115t182201...  2               callhome.reboot.unknown         0       uploaded    astrads-ds-support-xx6n8:
astrads-system  storage-callhome.reboot.unknown-20211115t182204...  3               callhome.reboot.unknown         0       uploaded    astrads-ds-support-qghnx:
----


== 下载 ASUP 捆绑包

您可以使用此命令下载本地收集的 ASUP 捆绑包。使用 ` -o < 位置 >` 指定当前工作目录以外的位置：

[listing]
----
./kubectl-astrasds asup download <ASUP_bundle_name> -o <location>
----
[discrete]
== 了解更多信息

* https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp["如何将文件上传到 NetApp （需要登录）"^]

