---
settings:
  name: Astra Data Store
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr
sidebar:
  entries:
  - title: Astra 数据存储文档
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: get-started
  - section: use
  - section: support
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解 Astra 数据存储
      url: "/concepts/intro.html"
    - title: Astra Data Store 预览版中的内容
      url: "/release-notes/whats-new.html"
    - title: 试用
      url: "/get-started/install-ads.html#edit-and-apply-the-astra-data-store-license"
    - title: 安装 Astra Data Store 预览版
      url: "/get-started/install-ads.html"
    - title: 设置 Astra Data Store 预览
      url: "/get-started/setup-ads.html"
  - title: 使用 Astra Data Store 预览版
    links:
    - title: 使用 kubectl 命令进行管理
      url: "/use/kubectl-commands-ads.html"
    - title: 使用 Cloud Insights 监控指标
      url: "/use/monitor-with-cloud-insights.html"
    - title: 监控事件日志
      url: "/use/configure-endpoints.html"
    - title: Astra 控制中心集成
      url: "/use/ads-acc-ui.html"
  - title: 演示教程
    links:
    - title: Kubernetes 的未来
      url: https://cloud.netapp.com/astra-data-store
    - title: Astra Data Store 预览演示
      url: https://netapp.hubs.vidyard.com/watch/aDmgkBbJhUTZAGmH5XKimA?
  - title: 博客社区
    links:
    - title: Astra 博客
      url: https://cloud.netapp.com/blog/topic/astra
    - title: '" 容器 " 通道可宽延'
      url: https://netapp.io/slack
    - title: Kubernetes Hub
      url: https://cloud.netapp.com/kubernetes-hub
    - title: 如何获取帮助
      url: "/support/get-help.html"
