---
sidebar: sidebar 
permalink: get-started/install-ads.html 
keywords: astra data store, install, deploy, openshift, astra control center, rancher, anthos 
summary: 您可以使用Kubernetes本机命令或使用Astra控制中心中的UI安装Astra数据存储。 
---
= 安装 Astra 数据存储
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


您可以使用Kubernetes本机命令或使用Astra控制中心中的UI安装Astra数据存储。



== 安装选项

* *使用Kubernetes本机命令*：要使用Kubernetes本机命令安装Astra Data Store、请完成中所述的安装步骤 <<Install Astra Data Store,此操作步骤>>。
* *使用Astra控制中心*：要使用Astra控制中心安装Astra数据存储库、请完成中所述的安装步骤 <<Install Astra Data Store using Astra Control Center,此操作步骤>>。




== 您将需要什么

* link:requirements.html["开始安装之前、请为部署Astra Data Store准备您的环境"]。
* 访问 https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["NetApp 支持站点"^]。 https://www.netapp.com/cloud-services/astra/data-store-form/["注册"^] 如果您还没有完全访问的NetApp支持站点帐户、请下载评估版。
* 答 link:../get-started/requirements.html#licensing["NetApp 许可证文件（ NLF ）"] 用于Astra数据存储。下载许可证的说明将在您之后发送给您 https://www.netapp.com/cloud-services/astra/data-store-form["注册"^]。
* 具有活动上下文集群管理员权限的活动 kubeconfig 。
* 了解 link:../get-started/faq-ads.html#installation-and-use-of-astra-data-store-on-a-kubernetes-cluster["角色和权限"] 由Astra数据存储使用。




== 安装 Astra 数据存储

标准Kubernetes集群的Astra数据存储安装过程将指导您完成以下高级步骤。此外、还介绍了适用于Red Hat OpenShift容器平台(OCP)环境的其他安装步骤。

* <<Download the Astra Data Store bundle and extract the images>>
* <<Copy the binary and push images to your local registry>>
* <<OpenShift procedure>>
* <<Install the Astra Data Store operator>>
* <<Deploy the Astra Data Store version YAML>>
* <<Apply the Astra Data Store license>>
* <<Install the Astra Data Store cluster>>
* <<Understand deployment-related events>>



NOTE: 要将Astra Data Store与Google Anthos结合使用、请完成以下安装步骤、然后将Astra Data Store集群添加到您的Anthos环境中。


NOTE: 要在Rancher RKE环境中安装Astra数据存储、请完成以下安装步骤、并将Rancher命令替换为kubectl命令。



=== 下载Astra Data Store软件包并提取映像

. 登录到 https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["NetApp 支持站点"^] 并下载Astra数据存储捆绑包(`Astra_Data_Store_2022.05.01.tar`)。
+

NOTE: 如果要查找早期版本的捆绑包的说明、请参见 link:../ads-earlier-versions.html["该版本的文档"]。

. （可选）使用以下命令验证捆绑包的签名：
+
[listing]
----
openssl dgst -sha256 -verify Astra_Data_Store_2022.05.01.pub -signature Astra_Data_Store_2022.05.01.sig 2022.12.01_ads.tar
----
. 创建目录：
+
[listing]
----
mkdir Astra_Data_Store_2022.05.01
cd Astra_Data_Store_2022.05.01
----
. 提取映像：
+
[listing]
----
tar -xvf <path to tar file>/Astra_Data_Store_2022.05.01.tar
----
+

NOTE: 这些图像将提取到工作目录中创建的`astrads/images`目录中。





=== 将二进制文件和推送映像复制到本地注册表

. 将kubectl-astrad二进制文件从用于提取映像的目录复制到安装了K8s kubectl二进制文件的标准路径(在以下示例中使用`/usr/bin/`作为路径)。kubectl-astrad是一个自定义kubectl扩展、用于安装和管理Astra数据存储集群。
+

TIP: 使用`which kubectl`命令查找安装kubectl二进制文件的路径。

+
[listing]
----
cp -p ./astrads/bin/kubectl-astrads /usr/bin/.
----
. 将Astra Data Store映像目录中的文件添加到本地注册表中。
+

NOTE: 有关自动加载映像的信息，请参见下面的示例脚本。

+
.. 登录到注册表：
+
[listing]
----
docker login [your_registry_path]
----
.. 将环境变量设置为要推送Astra数据存储映像的注册表路径；例如、`repo.company.com`。
+
[listing]
----
export REGISTRY=repo.company.com/astrads
----
.. 运行脚本将映像加载到 Docker ，标记映像，并将这些映像推送到本地注册表：
+
[listing]
----
for astraImageFile in $(ls astrads/images/*.tar) ; do
   astraImage=$(docker load --input ${astraImageFile} | sed 's~Loaded image: ~~')
   astraImageShort=`echo $astraImage | sed 's~.*/~~'`
   docker tag ${astraImage} ${REGISTRY}/${astraImageShort}
   docker push ${REGISTRY}/${astraImageShort}
done
sed -i 's~\[YOUR REGISTRY\]~'${REGISTRY}'~' ./astrads/manifests/*.yaml
----






=== OpenShift 操作步骤

以下操作步骤 仅用于在Red Hat OpenShift容器平台(OCP)上部署。跳过此操作步骤 以在非OCP Kubernetes集群上部署。

* 创建命名空间以部署Astra数据存储
* 创建自定义 SCC
* 创建角色和角色绑定


.详细信息
====
创建一个`astrads-system`命名空间、其中将安装所有Astra Data Store组件。

只有在Red Hat OpenShift容器平台(OCP)上部署时、才需要执行以下步骤。

. 创建命名空间：
+
[listing]
----
kubectl create -f ads_namespace.yaml
----
+
示例： ads_namespace.yaml

+
[listing]
----
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: operator
  name: astrads-system
----


OpenShift 使用安全上下文约束（ SCC ）来控制 Pod 可以执行的操作。默认情况下，任何容器的执行都将获得受限的 SCC ，并且仅获得该 SCC 定义的功能。

受限SCC不提供Astra Data Store集群Pod所需的权限。使用此操作步骤 为Astra数据存储提供所需的权限(在示例中列出)。

将自定义SCC分配给Astra Data Store命名空间的默认服务帐户。

只有在 Red Hat OpenShift 容器平台（ OCP ）上部署时，才需要执行以下步骤。

. 创建自定义 SCC ：
+
[listing]
----
kubectl create -f ads_privileged_scc.yaml
----
+
示例： ads_privileged_scc.yaml

+
[listing]
----
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'ADS privileged. Grant with caution.'
    release.openshift.io/create-only: "true"
  name: ads-privileged
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:astrads-system:default
volumes:
- '*'
----
. 使用 `oc get SCC` 命令显示新添加的 SCC ：
+
[listing]
----
# oc get scc/ads-privileged
NAME           PRIV  CAPS  SELINUX  RUNASUSER FSGROUP   SUPGROUP  PRIORITY   READONLYROOTFS  VOLUMES
ads-privileged true  ["*"] RunAsAny RunAsAny  RunAsAny  RunAsAny  <no value> false           ["*"]
#
----


创建Astra数据存储的默认服务帐户要使用的所需角色和角色绑定。

以下YAML定义可分配`astrads.netapp.io` API组中的Astra Data Store资源所需的各种角色(通过绑定)。

只有在 Red Hat OpenShift 容器平台（ OCP ）上部署时，才需要执行以下步骤。

. 创建定义的角色和角色绑定：
+
[listing]
----
kubectl create -f oc_role_bindings.yaml
----
+
示例： oc_role_Bindings.yaml

+
[listing]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privcrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ads-privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-scc-rolebinding
  namespace: astrads-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privcrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: astrads-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ownerref
  namespace: astrads-system
rules:
- apiGroups:
  - astrads.netapp.io
  resources:
  - '*/finalizers'
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: or-rb
  namespace: astrads-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ownerref
subjects:
- kind: ServiceAccount
  name: default
  namespace: astrads-system
----


====


=== 配置私有映像注册表

对于某些环境、您可以将配置更改为从使用机密的专用注册表中提取映像。

. 创建`astrads-system`命名空间、除非您已在上一步中创建了此命名空间：
+
[listing]
----
kubectl create namespace astrads-system
----
. 创建密钥：
+
[listing]
----
kubectl create secret docker-registry <secret-name> -n astrads-system --docker-server=<registry name> --docker-username= <registry username> --docker-password=<registry user password>
----
. 向服务帐户添加机密配置信息：
+
[listing]
----
kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "<secret-name>"}]}' -n astrads-system
----
+

NOTE: 这些更改将在您使用时应用 <<Install the Astra Data Store operator,安装Astra数据存储操作员>>。





=== 安装Astra数据存储操作员

. 列出Astra数据存储清单：
+
[listing]
----
ls astrads/manifests/*yaml
----
+
响应：

+
[listing]
----
astrads/manifests/monitoring_operator.yaml
astrads/manifests/astradscluster.yaml
astrads/manifests/astradsversion.yaml
astrads/manifests/astradsoperator.yaml
astrads/manifests/vasa_asup_certs.yaml
astrads/manifests/manifest.yaml
astrads/manifests/configuration.yaml
----
. 使用`kubectl apply`部署操作员：
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradsoperator.yaml
----
+
响应：

+

NOTE: 根据您执行的是标准安装还是、命名空间响应可能会有所不同 link:../get-started/install-ads.html#openshift-procedure["OpenShift容器平台安装"]。

+
[listing]
----
namespace/astrads-system created
customresourcedefinition.apiextensions.k8s.io/astradsadddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsautosupports.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradscloudsnapshots.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsclusters.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsexportpolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsfaileddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradskeyproviders.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradslicenses.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnfsoptions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodeinfoes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodemanagements.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsqospolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradssearkeyrotaterequests.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsversions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumefiles.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumesnapshots.astrads.netapp.io created
role.rbac.authorization.k8s.io/astrads-astrads-system-admin-role created
role.rbac.authorization.k8s.io/astrads-astrads-system-reader-role created
role.rbac.authorization.k8s.io/astrads-astrads-system-writer-role created
role.rbac.authorization.k8s.io/astrads-leader-election-role created
role.rbac.authorization.k8s.io/astrads-manager-role created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-admin-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-reader-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-writer-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astradsautosupport-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsautosupport-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsexportpolicy-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsexportpolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsfaileddrive-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsfaileddrive-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnfsoption-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnfsoption-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodeinfo-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodeinfo-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodemanagement-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodemanagement-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsqospolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsversion-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsversion-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumefile-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumefile-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumesnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumesnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-manager-role created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-admin-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-reader-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-writer-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-admin-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-reader-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-writer-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
configmap/astrads-autosupport-cm created
configmap/astrads-firetap-cm created
configmap/astrads-kevents-asup created
configmap/astrads-metrics-cm created
secret/astrads-autosupport-certs created
secret/astrads-webhook-server-cert created
service/astrads-webhook-service created
deployment.apps/astrads-operator created
----
. 验证 Astra 数据存储操作员 POD 是否已启动且正在运行：
+
[listing]
----
kubectl get pods -n astrads-system
----
+
响应：

+
[listing]
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-operator-5ffb94fbf-7ln4h    1/1     Running   0          17m
----




=== 部署Astra Data Store版本YAML

. 使用`kubectl apply`进行部署：
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradsversion.yaml
----
. 验证 Pod 是否正在运行：
+
[listing]
----
kubectl get pods -n astrads-system
----
+
响应：

+
[listing]
----
NAME                                          READY   STATUS    RESTARTS   AGE
astrads-cluster-controller-7f6f884645-xxf2n   1/1     Running   0          117s
astrads-ds-nodeinfo-2jqnk                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-dbk7v                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-rn9tt                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-vsmhv                     1/1     Running   0          2m7s
astrads-license-controller-fb8fd56bc-bxq7j    1/1     Running   0          2m2s
astrads-operator-5ffb94fbf-7ln4h              1/1     Running   0          2m10s
----




=== 应用Astra Data Store许可证

. 应用从NetApp获得的NetApp许可证文件(NLF)。运行命令之前，请输入您所在集群的名称（` <Astra-Data-Store-cluster-name>` ） <<Install the Astra Data Store cluster,即将部署>> 或已部署许可证文件的路径（` <file_path/file.txt>` ）：
+
[listing]
----
kubectl astrads license add --license-file-path <file_path/file.txt> --ads-cluster-name <Astra-Data-Store-cluster-name> -n astrads-system
----
. 验证是否已添加此许可证：
+
[listing]
----
kubectl astrads license list
----
+
响应：

+
[listing]
----
NAME                    ADSCLUSTER               VALID PRODUCT          EVALUATION  ENDDATE     VALIDATED
e100000006-ads-capacity astrads-example-cluster  true  Astra Data Store true        2023-01-23  2022-04-04T14:38:54Z
----




=== 安装Astra数据存储集群

. 打开 YAML 文件：
+
[listing]
----
vim ./astrads/manifests/astradscluster.yaml
----
. 编辑 YAML 文件中的以下值。
+

NOTE: 以下步骤将提供一个简化的 YAML 文件示例。

+
.. （必需） * 元数据 * ：在 `metadata` 中，将 `name` string 更改为集群名称。此集群名称必须与您在使用时使用的集群名称相同 <<Apply the Astra Data Store license,应用许可证>>。
.. （必需） * 规格 * ：在 `sPec` 中更改以下必需值：
+
*** 根据您的许可证和Astra Data Store安装大小、将`adsNodeConfig`值更改为您的安装所需的值：
+
**** 小型：9个CPU和38个内存
**** 中：23个CPU和94个内存


*** (可选)删除围绕`adsNodeSelector`部分的注释。如果要将Astra数据存储限制为仅安装在选定的工作节点池上、请配置此设置。
*** (可选)指定在4-16之间应在Astra数据存储集群中使用的特定节点数。
*** 将 `mVIP` 字符串更改为可从集群中的任何工作节点路由的浮动管理 IP 的 IP 地址。
*** 在 `adsDataNetworks` 中，添加一个逗号分隔的浮动 IP 地址列表（`addresses` ），这些地址可从要挂载 NetApp 卷的任何主机路由。每个节点使用一个浮动 IP 地址。数据网络IP地址的数量应至少与Astra数据存储节点的数量相同。对于Astra数据存储、这意味着至少需要4个地址、如果您计划稍后扩展集群、则最多需要16个地址。
*** 在 `adsDataNetworks` 中，指定数据网络使用的网络掩码。
*** 在 `adsNetworkInterfaces` 中，将 ` <mgmt_interface_name>` 和 ` <cluster_and_storage_interface_name>` 值替换为要用于管理，集群和存储的网络接口名称。如果未指定名称，则节点的主接口将用于管理，集群和存储网络连接。此外、请务必删除`adsNetworkInterfaces`部分的注释。
+

NOTE: 集群和存储网络必须位于同一接口上。Astra数据存储管理接口应与Kubernetes节点的管理接口相同。



.. （可选） * 显示器配置 * ：如果要配置 <<Install the monitoring operator,监控操作员>> （如果您不使用 Astra Control Center 进行监控，则可选），从部分中删除注释，添加应用代理 CR （监控操作员资源）的命名空间（默认值为 `netapp-monitoring` ），然后添加您在先前步骤中使用的注册表的 repo路径 （`yor_registry_path` ）。
.. （可选） * 自动支持配置 * ：保留 link:../support/autosupport.html["AutoSupport"] 默认值，除非您需要配置代理：
+
*** 对于 `proxyURL` ，使用要用于 AutoSupport 捆绑包传输的端口设置代理的 URL 。


+

NOTE: 为了简明起见、我们从以下YAML示例中删除了一些注释。



+
[listing, subs="+quotes"]
----
apiVersion: astrads.netapp.io/v1beta1
kind: AstraDSCluster
*metadata:*
  *name: astrads-cluster-name*
  namespace: astrads-system
*spec:*
  *adsNodeConfig:*
    *cpu: 9*
    *memory: 38*
  # [Optional] Specify node selector labels to select the nodes for creating ADS cluster
  # adsNodeSelector:
  #   matchLabels:
  #     customLabelKey: customLabelValue
  adsNodeCount: 4
  *mvip: ""*
  *adsDataNetworks:*
    *- addresses: ""*
      *netmask:*
  # Specify the network interface names to use for management, cluster and storage networks.
  # If none are specified, the node's primary interface will be used for management, cluster and storage networking.
  # To move the cluster and storage networks to a different interface than management, specify all three interfaces to use here.
  # NOTE: The cluster and storage networks need to be on the same interface.
  *adsNetworkInterfaces:*
    *managementInterface: "<mgmt_interface_name>"*
    *clusterInterface: "<cluster_and_storage_interface_name>"*
    *storageInterface: "<cluster_and_storage_interface_name>"*
  # [Optional] Provide a monitoring config to be used to setup/configure a monitoring agent.
 *# monitoringConfig:*
   *# namespace: "netapp-monitoring"*
   *# repo: "[YOUR REGISTRY]"*
  autoSupportConfig:
    autoUpload: true
    enabled: true
    coredumpUpload: false
    historyRetentionCount: 25
    destinationURL: "https://support.netapp.com/put/AsupPut"
    # ProxyURL defines the URL of the proxy with port to be used for AutoSupport bundle transfer
    *# proxyURL:*
    periodic:
      - schedule: "0 0 * * *"
        periodicconfig:
        - component:
            name: storage
            event: dailyMonitoring
          userMessage: Daily Monitoring Storage AutoSupport bundle
          nodes: all
        - component:
            name: controlplane
            event: daily
          userMessage: Daily Control Plane AutoSupport bundle
----
. 使用 `kubectl apply` 部署集群：
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradscluster.yaml
----
. 等待几分钟，以完成集群创建操作，然后验证 Pod 是否正在运行：
+
[listing]
----
kubectl get pods -n astrads-system
----
+
响应示例：

+
[listing]
----
NAME                                              READY     STATUS    RESTARTS    AGE
astrads-cluster-controller-7c67cc7f7b-2jww2       1/1       Running   0           7h31m
astrads-deployment-support-788b859c65-2qjkn       3/3       Running   19          12d
astrads-ds-astrads-cluster-1ab0dbc-j9jzc          1/1       Running   0           5d2h
astrads-ds-astrads-cluster-1ab0dbc-k9wp8          1/1       Running   0           5d1h
astrads-ds-astrads-cluster-1ab0dbc-pwk42          1/1       Running   0           5d2h
astrads-ds-astrads-cluster-1ab0dbc-qhvc6          1/1       Running   0           8h
astrads-ds-nodeinfo-gcmj8                         1/1       Running   1           12d
astrads-ds-nodeinfo-j826x                         1/1       Running   3           12d
astrads-ds-nodeinfo-vdthh                         1/1       Running   3           12d
astrads-ds-nodeinfo-xwgsf                         1/1       Running   0           12d
astrads-ds-support-828vw                          2/2       Running   2           5d2h
astrads-ds-support-astrads-example-cluster-cfzts  2/2       Running   0           8h
astrads-ds-support-astrads-example-cluster-nzkkr  2/2       Running   15          7h49m
astrads-ds-support-astrads-example-cluster-xxbnp  2/2       Running   1           5d2h
astrads-license-controller-86c69f76bb-s6fb7       1/1       Running   0           8h
astrads-operator-79ff8fbb6d-vpz9m                 1/1       Running   0           8h
----
. 验证集群部署进度：
+
[listing]
----
kubectl get astradscluster -n astrads-system
----
+
响应示例：

+
[listing]
----
NAME                        STATUS    VERSION      SERIAL NUMBER    MVIP       AGE

astrads-example-cluster     created   2022.05.0-X  e100000006       10.x.x.x   13m
----




=== 了解与部署相关的事件

在集群部署期间，操作状态应从 `blank` 更改为 `in progress` 更改为 `created` 。集群部署将持续大约 8 到 10 分钟。要在部署期间监控集群事件，您可以运行以下命令之一：

[listing]
----
kubectl get events --field-selector involvedObject.kind=AstraDSCluster -n astrads-system
----
[listing]
----
kubectl describe astradscluster <cluster name> -n astrads-system
----
以下是部署期间的关键事件：

|===
| 事件 | 消息和重要性 


| 已选择ControlPlaneNodesS | 已成功选择【编号】控制平面节点以加入ADS集群。Astra数据存储操作员确定了具有CPU、内存、存储和网络的足够多节点、以创建Astra数据存储集群。 


| ADSClusterCreateInProProgress | Astra Data Store集群控制器已启动集群创建操作。 


| ADSClusterCreateSuccessess | 已成功创建集群。 
|===
如果集群的状态未更改为 `in progress` ，请查看操作员日志，了解有关节点选择的更多详细信息：

[listing]
----
kubectl logs -n astrads-system <astrads operator pod name>
----
如果集群状态停留在`in progress`、请检查集群控制器的日志：

[listing]
----
kubectl logs -n astrads-system <astrads cluster controller pod name>
----


== 使用Astra控制中心安装Astra数据存储

要在Astra控制中心中部署和使用Astra数据存储、请执行以下操作。

.您需要什么？ #8217 ；将需要什么
* 您已查看 <<What you'll need,Astra数据存储的一般前提条件>>。
* 您已安装Astra控制中心。


.步骤
. https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html#add-a-storage-backend["使用Astra控制中心部署Astra数据存储"^]。




== 下一步行动

* * Kubernetes本机部署和第三方分发版*：通过执行其他操作完成Astra Data Store部署 link:setup-ads.html["设置任务"]。
* * Astra控制中心*：如果您已使用Astra控制中心部署Astra数据存储、则无需遵循这些原则 link:../get-started/setup-ads.html#configure-astra-data-store-monitoring["设置任务"] 除非您要配置任何其他监控选项。部署Astra数据存储后、您可以使用Astra控制中心UI完成以下任务：
+
** https://docs.netapp.com/us-en/astra-control-center/use/monitor-protect.html["监控Astra数据存储资产的运行状况"^]。
** https://docs.netapp.com/us-en/astra-control-center/use/manage-backend.html["管理Astra Data Store后端存储"^]。
** https://docs.netapp.com/us-en/astra-control-center/use/view-dashboard.html["监控节点，磁盘和永久性卷声明（ PVC ）"^]。



