---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: 首先验证对您的环境的支持。 
---
= Astra 数据存储要求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


首先验证您的环境是否满足Astra Data Store要求。

Astra数据存储既支持裸机部署、也支持基于VM的部署。Astra数据存储集群可以在具有四个或更多工作节点的Kubernetes集群上运行。Astra Data Store软件可以与在同一Kubernetes集群上运行的其他应用程序共存。

* <<Kubernetes worker node resources>>
* <<Hardware and software>>
* <<Networking>>
* <<Astra Trident>>
* <<Container Network Interfaces>>
* <<Licensing>>



NOTE: 如果您计划从Astra控制中心管理Astra数据存储集群、请确保您的Astra数据存储集群符合 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["由 Astra 控制中心管理的集群的要求"^] 除了此处概述的要求之外。



== Kubernetes工作节点资源

以下是在Kubernetes集群中每个工作节点上分配给Astra Data Store软件所需的资源要求：

|===
| 资源 | 最小值 | 最大值 


| Astra数据存储集群中的节点数 | 4. | 16. 


| 数据驱动器的数量  a| 
* 3 （存在单独的缓存设备）
* 4 （如果不存在缓存设备）

| 14 


| 数据驱动器大小 | 100 GiB | 4 TiB 


| 可选缓存设备的数量 | 1 (8 GiB大小) | 不适用 
|===
Astra数据存储支持每个Kubernetes工作节点的以下vCPU和RAM组合：

* 9个vCPU、RAM为38 GiB
* 23个vCPU、94 GiB RAM



NOTE: 为了获得最佳写入性能，您应配置一个专用的高持久性，低延迟，低容量缓存设备。

每个工作节点都有以下附加要求：

* 主机磁盘(启动)上要存储Astra Data Store日志文件的可用空间为100 GiB或更大。
* 至少为集群，数据和管理流量提供一个 10GbE 或更快的网络接口。此外，还可以使用一个额外的 1GbE 或更快的接口来隔离管理流量。




== 硬件和软件：

已在以下硬件平台、软件和存储配置上验证Astra Data Store软件。请访问 link:../support/get-help-ads.html["NetApp 社区支持"] 如果您的 Kubernetes 集群配置不同。



=== 硬件平台

* Dell R640
* Dell R740
* HPE DL360
* HPE DL380
* 联想SR630
* 联想SR650



NOTE: 基于VM的部署还可以使用上列为兼容的服务器 https://www.vmware.com/resources/compatibility/search.php["VMware 兼容性指南"^]。



=== 存储

Astra数据存储已通过SATA、SAS和NVMe TLC SSD的验证。

对于基于VM的部署、您可以使用以虚拟磁盘或直通驱动器形式提供的驱动器。

[NOTE]
====
* 如果主机在硬件 RAID 控制器后使用 SSD ，请将硬件 RAID 控制器配置为使用 " 直通 " 模式。
* 每个驱动器都应具有唯一的序列号。在虚拟机创建期间，在虚拟机高级设置中添加属性 `disk.enableid=true` 。


====


=== 软件

* 虚拟机管理程序：Astra Data Store已通过使用vSphere 7.0部署基于VMware的虚拟机的验证。Astra数据存储不支持基于KVM的部署。
* 已在以下主机操作系统上验证Astra数据存储：
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS （ RHCOS ）
** CentOS 8
** Ubuntu 20.04


* Astra数据存储已通过以下Kubernetes分发版的验证：
+
** Red Hat OpenShift 4.6到4.9
** Google Anthos 1.8到1.10
** Kubernetes 1.20至1.23
** Rancher RKE1.3.3





NOTE: Astra数据存储需要使用Astra Trident进行存储配置和编排。支持Astra Trident 21.10.1至22.04版。请参见 link:setup-ads.html#install-astra-trident["Astra Trident 安装说明"]。



== 网络

Astra数据存储要求每个集群为MVIP配置一个IP地址。它必须是与 MIP 位于同一子网中的未使用或未配置的 IP 地址。Astra数据存储管理接口应与Kubernetes节点的管理接口相同。

此外，还可以按下表所述配置每个节点：


NOTE: 此表使用了以下缩写词： mip ： management IP address cip ： cluster ip address MVIP ： management virtual IP address

|===
| Configuration | 所需的 IP 地址 


| 每个节点一个网络接口  a| 
* 每个节点两（ 2 ）个：
+
** MIP/CIP ：每个节点的管理接口上有一（ 1 ）个预配置的 IP 地址
** Data IP ：在与 MIP 相同的子网中，每个节点一（ 1 ）个未使用或未配置的 IP 地址






| 每个节点两个网络接口  a| 
* 每个节点三个：
+
** MIP ：每个节点的管理接口上有一（ 1 ）个预配置的 IP 地址
** CIP ：在与 MIP 不同的子网中，每个节点的数据接口上有一（ 1 ）个预先配置的 IP 地址
** Data IP ：在与 CIP 相同的子网中，每个节点一（ 1 ）个未使用或未配置的 IP 地址




|===

NOTE: 这些配置中不使用任何 VLAN 标记。



=== 防火墙注意事项

在强制实施网络防火墙流量筛选的环境中、必须将防火墙配置为允许传入下表中列出的端口和协议的流量。"IP Address"列使用以下缩写：

* mip：每个节点的管理接口上的主IP地址
* cip：每个节点的集群接口上的主IP地址
* DIP：在节点上配置的一个或多个数据IP地址
* MVIP：在一个集群节点上配置的管理虚拟IP地址


|===
| 端口/协议 | IP 地址 | 目的 | 注释： 


| 111 TCP | DIP | NFS | 数据IP在运行时在集群节点之间移动。每个节点应允许所有数据IP (或整个子网)使用此流量。 


| 442/TCP | MIP | API |  


| 635 TCP | DIP | NFS | 数据IP在运行时在集群节点之间移动。每个节点应允许所有数据IP (或整个子网)使用此流量。 


| 2010/UDP | CIP | 集群/节点发现 | 包括与UDP端口2010之间的单播和广播流量、包括回复。 


| 2049 TCP | DIP | NFS | 数据IP在运行时在集群节点之间移动。每个节点应允许所有数据IP (或整个子网)使用此流量。 


| 2181-2183/TCP | CIP | 分布式通信 |  


| 2443/TCP | MIP | API |  


| 2443/TCP | MVIP | API | MVIP地址可由任何集群节点托管、并可在运行时根据需要重新定位。 


| 4000-4006/TCP | CIP | 集群内RPC |  


| 4045-4046/ TCP | DIP | NFS | 数据IP在运行时在集群节点之间移动。每个节点应允许所有数据IP (或整个子网)使用此流量。 


| 7700/TCP | CIP | 会话管理器 |  


| 9919/TCP | MIP | DMS-API |  


| 9920/TCP | DIP | DMS-REST服务器 |  


| ICMP | CIP + DIP | 节点内通信、运行状况检查 | 数据IP在运行时在集群节点之间移动。每个节点应允许所有数据IP (或整个子网)使用此流量。 
|===


== Astra Trident

Astra数据存储要求应用程序Kubernetes集群运行Astra Trident进行存储配置和编排。支持Astra Trident 21.10.1至22.04版。Astra数据存储可配置为 link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["存储后端"] 使用 Astra Trident 配置永久性卷。



== 容器网络接口

Astra数据存储已通过以下容器网络接口(CNI)的验证。

* 适用于RKE集群的Calico
* 适用于 Vanilla Kubernetes 集群的 Calico 和 Weave Net CNI
* 适用于 Red Hat OpenShift 容器平台（ OCP ）的 OpenShift SDN
* Cilium for Google Anthos


[NOTE]
====
* 随Cilium CNI部署的Astra数据存储需要portmap插件才能支持hostPort。您可以通过将`cnis-canding-mode：portmap`添加到cilial-config configMap并重新启动Cilium Pod来启用CNI链模式。
* 只有Calico和OpenShift SDN CNI才支持启用了防火墙的配置。


====


== 许可

要启用全部功能、Astra数据存储需要有效的许可证。

https://www.netapp.com/cloud-services/astra/data-store-form/["请在此处注册"^] 以获取Astra Data Store许可证。注册后，系统将向您发送许可证下载说明。



== 下一步行动

查看 link:quick-start.html["快速入门"] 概述。



== 有关详细信息 ...

link:capabilities.html["Astra数据存储限制"]
